export const PROJECTS_DATA = {
  north: {
    id: "north",
    wallName: "Pared 1 (Norte) • TV Display",
    title: "Contaco",
    category: "SAAS",
    status: {
      label: "En Producción",
      detail: "SaaS en vivo con uso real — contaco.store",
      tone: "live",
    },
    preview: "WhatsApp → venta lista para el SAT",
    icon: "fa-tv",
    accentColor: "#6366f1",
    description:
      "Plataforma para restaurantes en México que une WhatsApp nativo + POS + contabilidad invisible lista para el SAT. El pedido se convierte automáticamente en venta y en los números exactos que el dueño necesita para declarar.",
    tech: ["Sveltekit", "MongoDB", "Tailwind CSS", "Better auth"],
    github: "https://github.com/DiegoAvenda/conta",
    demo: "https://contaco.store",
    type: "tv",
    features: [
      "Pedidos por WhatsApp nativo que se convierten en venta automáticamente",
      "POS integrado con contabilidad invisible lista para el SAT",
      "Los números exactos para declarar, sin esfuerzo contable",
    ],
  },
  east: {
    id: "east",
    wallName: "Pared 2 (Este) • Pizarrón de Trabajo",
    title: "El 7",
    category: "Ray casting game",
    status: {
      label: "Demo Jugable",
      detail: "Proyecto de portafolio — demo pública, sin uso comercial",
      tone: "demo",
    },
    preview: "Ray casting en vivo sobre Canvas 2D",
    icon: "fa-chalkboard",
    accentColor: "#10b981",
    description: "Pseudo 3d game estilo wolfenstain 3d",
    tech: ["Canvas 2D API", "Ray casting", "Javascript"],
    github: "https://github.com/DiegoAvenda/el-7",
    demo: "https://neo-diego-2d.vercel.app/",
    type: "whiteboard",
    features: [
      "Motor de ray casting estilo Wolfenstein 3D sobre Canvas 2D",
      "Renderizado pseudo-3D en tiempo real con JavaScript puro",
      "Jugable en el navegador sin dependencias externas",
    ],
  },
  south: {
    id: "south",
    wallName: "Pared 3 (Sur) • Cuadro Galería Artística",
    title: "3D game",
    category: "Generative Canvas & Shaders",
    status: {
      label: "Demo Jugable",
      detail: "Proyecto de portafolio — demo pública, sin uso comercial",
      tone: "demo",
    },
    preview: "Shooter 3D con shaders GLSL en WebGL",
    icon: "fa-image",
    accentColor: "#f59e0b",
    description: "Third person shotter game with three.js",
    tech: ["WebGL", "GLSL", "Three.js"],
    github: "https://github.com/DiegoAvenda/neo-diego-3d-game",
    demo: "https://neo-diego-3d-game.vercel.app/",
    type: "picture",
    features: [
      "Shooter en tercera persona construido con Three.js",
      "Shaders GLSL y renderizado WebGL en tiempo real",
      "Jugable directo en el navegador",
    ],
  },
  west: {
    id: "west",
    wallName: "Pared 4 (Oeste) • Monitor Holográfico",
    title: "Reactivity engine",
    category: "Fine-grained reactivity",
    status: {
      label: "Prototipo Técnico",
      detail: "Laboratorio experimental de reactividad",
      tone: "prototype",
    },
    preview:
      "Laboratorio interactivo que recrea y visualiza los fundamentos de reactividad de Vue y Solid.",
    icon: "fa-microchip",
    accentColor: "#d946ef",
    description:
      "Exploración experimental de los mecanismos internos detrás de la reactividad de Vue y Solid. El proyecto implementa desde cero dos modelos diferentes: reactividad basada en Proxy con tracking y triggering dinámico, y reactividad basada en signals con getters, setters y dependencias granulares. Un toggle permite comparar ambos modelos y observar sus dependencias en tiempo real.",
    tech: ["JavaScript", "Proxy API", "WeakMap", "Set / Map", "Signals"],
    github: "https://github.com/DiegoAvenda/reactivity-engine",
    demo: "https://reactivity-engine-seven.vercel.app/",
    type: "holo",
    features: [
      "Implementación desde cero de un sistema reactivo basado en Proxy inspirado en el modelo de Vue",
      "Implementación independiente de signals con getters y setters inspirada en el modelo de Solid",
      "Tracking dinámico de dependencias durante la ejecución de efectos",
      "Cleanup automático de dependencias obsoletas",
      "Comparación interactiva entre mutaciones directas y setters explícitos",
      "Visualización en tiempo real de las dependencias activas de cada efecto",
      "Caché de Proxies mediante WeakMap para preservar referencias",
      "Sistema de efectos reactivos y triggering granular sin depender de Vue o Solid",
    ],
  },
}

export const ROOM_SIZE = { width: 18, height: 9, depth: 18 }

export const CAMERA_PRESETS = {
  overview: { pos: { x: 0, y: 1, z: 6 }, target: { x: 0, y: 0, z: 0 } },
  north: { pos: { x: 0, y: 0.5, z: -2.5 }, target: { x: 0, y: 0.8, z: -8.9 } },
  east: { pos: { x: 2.5, y: 0.5, z: 0 }, target: { x: 8.9, y: 0.8, z: 0 } },
  south: { pos: { x: 0, y: 0.5, z: 2.5 }, target: { x: 0, y: 0.8, z: 8.9 } },
  west: { pos: { x: -2.5, y: 0.5, z: 0 }, target: { x: -8.9, y: 0.8, z: 0 } },
}
