export const PROJECTS_DATA = {
  north: {
    id: "north",
    wallName: "Pared 1 (Norte) • TV Display",
    title: "Contaco",
    category: "SaaS B2B / FoodTech",
    status: {
      label: "En Producción",
      detail: "Desplegado en producción con tracción y usuarios activos — contaco.store",
      tone: "live",
    },
    preview: "Ecosistema integral para restaurantes: eCommerce delivery, POS y conciliación fiscal automatizada (SAT)",
    icon: "fa-tv",
    accentColor: "#6366f1",
    description:
      "Plataforma SaaS B2B end-to-end diseñada para optimizar la operación gastronómica en México. Unifica canales de venta digital (delivery) con un Punto de Venta (POS) centralizado y un motor de contabilidad en tiempo real, transformando cada transacción operativa en métricas y registros listos para cumplimiento tributario sin fricción.",
    tech: ["Sveltekit", "MongoDB", "Tailwind CSS", "Better auth", "Node.js"],
    github: "https://github.com/DiegoAvenda/conta",
    demo: "https://contaco.store",
    type: "tv",
    features: [
      "Portal de pedidos en línea optimizado para conversión móvil y autogestión de clientes",
    "Punto de Venta (POS) reactivo para gestión de comandas, mesas y flujo de caja en tiempo real",
    "Motor de conciliación fiscal automática: registro y balance de ventas listo para declaraciones ante el SAT",
    "Arquitectura desacoplada con autenticación segura y persistencia escalable de transacciones",
    ],
  },
  east: {
    id: "east",
    wallName: "Pared 2 (Este) • Pizarrón de Trabajo",
    title: "El 7",
    category: "Ray casting game",
    status: {
      label: "Demo Jugable",
      detail: "Proyecto de portafolio — demo pública, sin uso comercial",
      tone: "demo",
    },
    preview: "Ray casting en vivo sobre Canvas 2D",
    icon: "fa-chalkboard",
    accentColor: "#10b981",
    description: "Pseudo 3d game estilo wolfenstain 3d",
    tech: ["Canvas 2D API", "Ray casting", "Javascript"],
    github: "https://github.com/DiegoAvenda/el-7",
    demo: "https://neo-diego-2d.vercel.app/",
    type: "whiteboard",
    features: [
      "Motor de ray casting estilo Wolfenstein 3D sobre Canvas 2D",
      "Renderizado pseudo-3D en tiempo real con JavaScript puro",
      "Jugable en el navegador sin dependencias externas",
    ],
  },
  south: {
    id: "south",
    wallName: "Pared 3 (Sur) • Cuadro Galería Artística",
    title: "3D game",
    category: "Generative Canvas & Shaders",
    status: {
      label: "Demo Jugable",
      detail: "Proyecto de portafolio — demo pública, sin uso comercial",
      tone: "demo",
    },
    preview: "Shooter 3D con shaders GLSL en WebGL",
    icon: "fa-image",
    accentColor: "#f59e0b",
    description: "Third person shotter game with three.js",
    tech: ["WebGL", "GLSL", "Three.js"],
    github: "https://github.com/DiegoAvenda/neo-diego-3d-game",
    demo: "https://neo-diego-3d-game.vercel.app/",
    type: "picture",
    features: [
      "Shooter en tercera persona construido con Three.js",
      "Shaders GLSL y renderizado WebGL en tiempo real",
      "Jugable directo en el navegador",
    ],
  },
  west: {
    id: "west",
    wallName: "Pared 4 (Oeste) • Monitor Holográfico",
    title: "Fincheck",
    category: "Fullstack & Cloud Web App",
    status: {
      label: "Aplicación Web Completa",
      detail: "Gestor financiero personal y asesor patrimonial inteligente",
      tone: "Prodcution",
    },
    preview:
      "Plataforma interactiva de salud financiera personal con motor de analítica presupuestaria, diagnóstico 50/30/20 y proyecciones de inversión.",
    icon: "fa-microchip",
    accentColor: "#d946ef",
    description:
      "Aplicación financiera diseñada para transformar el control de gastos en decisiones patrimoniales estratégicas. Integra un motor de cálculo en tiempo real que evalúa presupuestos por categoría con alertas dinámicas de sobregasto, un diagnóstico de equilibrio basado en la regla 50/30/20 y un simulador interactivo de interés compuesto. Su arquitectura combina una experiencia reactiva instantánea en cliente con preparación cloud serverless mediante AWS Amplify Gen 2 (Cognito Auth y DynamoDB/AppSync) para aislamiento seguro de datos por usuario.",
    tech: ["Next.js",
    "React 19",
    "AWS Amplify Gen 2",
    "Tailwind CSS",
    "DynamoDB / AppSync",
    "Lucide Icons",],
    github: "https://github.com/DiegoAvenda/next-fincheck",
    demo: "https://master.d1iwsfzibgcp9c.amplifyapp.com/",
    type: "holo",
    features: [
     "Motor de cálculo financiero en tiempo real con Financial Health Score (0-100), tasa de ahorro y balance neto",
    "Control presupuestario por categoría con alertas preventivas (80%) y detección automática de sobrecostos",
    "Módulo de Asesor Inteligente con diagnóstico de distribución de ingresos bajo la regla 50/30/20",
    "Simulador interactivo de interés compuesto con aportaciones periódicas y comparativa de rendimientos de mercado",
    "Gestión integral (CRUD) de transacciones con desglose visual de gastos e integración preparada para AWS Cognito y DynamoDB",
    ],
  },
}

export const ROOM_SIZE = { width: 18, height: 9, depth: 18 }

export const CAMERA_PRESETS = {
  overview: { pos: { x: 0, y: 1, z: 6 }, target: { x: 0, y: 0, z: 0 } },
  north: { pos: { x: 0, y: 0.5, z: -2.5 }, target: { x: 0, y: 0.8, z: -8.9 } },
  east: { pos: { x: 2.5, y: 0.5, z: 0 }, target: { x: 8.9, y: 0.8, z: 0 } },
  south: { pos: { x: 0, y: 0.5, z: 2.5 }, target: { x: 0, y: 0.8, z: 8.9 } },
  west: { pos: { x: -2.5, y: 0.5, z: 0 }, target: { x: -8.9, y: 0.8, z: 0 } },
}
